# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy demo to github pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: cp src/config.ts.example src/config.ts 
    - run: npm run build
    - name: GitHub Pages Deploy
      uses: appleboy/gh-pages-action@v0.0.2
      with:
        # directory of content to publish
        pages_directory: dist 
        # directory of content to sync
        target_directory: spruchtbeutel
